[package]
name = "dlpark"
version = "0.2.0"
edition = "2021"
authors = ["SunDoge"]
license-file = "LICENSE"
description = "dlpack Rust binding for Python"
homepage = "https://crates.io/crates/dlpark"
documentation = "https://docs.rs/dlpark"
repository = "https://github.com/SunDoge/dlpark"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version = "0.18.3", features = ["extension-module"], optional = true }

[workspace]
members = ["examples/from_numpy", "examples/with_pyo3"]

[features]

default = ["pyo3"]

pyo3 = ["dep:pyo3"]
