[package]
name = "dlpark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project = "1.0.12"

[workspace]
members = ["example/from_numpy"]
